Usuario editar
GrupoDeEstudosEstagiariosSMN/Academus pull request #7
Opened 2023-05-04 19:45 UTC by rafaelgalvaolm

Finalização do usuario-editar

2023-05-04 19:57 UTC, thofalbo requested changes

2023-05-04 19:57 UTC, thofalbo commented on .gitignore
> +.fake
retirou vs, mas deixou o .fake?

2023-05-04 19:57 UTC, thofalbo commented on Academus.sln
> +# Visual Studio Version 17
visual studio 17?

2023-05-04 19:57 UTC, thofalbo commented on Academus.sln
> +EndGlobal
linha no final do codigo

2023-05-04 19:57 UTC, thofalbo commented on Core/Interfaces/Repositories/IUsuarioRepository.cs
>  }
linha no final do codigo.

2023-05-04 19:57 UTC, thofalbo commented on Data/Extensions/DbContextExtensions.cs
> +}
linha ao final do codigo

2023-05-04 19:57 UTC, thofalbo commented on Data/Repositories/UsuarioRepository.cs
> +            var entity = await _dbContext.Set<Usuario>().FindAsync(id);
Se você adicionou a extension, então deve utilizar a extension, e não o código alterado.

2023-05-04 19:57 UTC, thofalbo commented on Web/Controllers/UsuarioController.cs
> -            await _usuarioRepository.Deletar(idUsuario.Id);
Utilizar DeletarAsync para um metodo async

2023-05-04 19:57 UTC, thofalbo commented on Web/Controllers/UsuarioController.cs
>      }
linha ao final do codigo

2023-05-04 19:57 UTC, thofalbo commented on Web/ViewModels/Usuario/BuscarUsuarioViewModel.cs
>  }
linha ao final do codigo

2023-05-04 19:57 UTC, thofalbo commented on Web/Views/Usuario/_Cadastrar.cshtml
>        <hr>
não usar mais hr

2023-05-04 19:57 UTC, thofalbo commented on Web/Views/Usuario/_Cadastrar.cshtml
>        <hr>
colocar linha ao final do codigo

2023-05-04 19:57 UTC, thofalbo commented on Web/wwwroot/css/Pages/_buscar.css
> +}
linha ao final do codigo

2023-05-04 19:57 UTC, thofalbo commented on Web/wwwroot/js/Pages/usuario.js
>  })();
linha ao final do codigo.

2023-05-04 20:06 UTC, rafaelgalvaolm commented on Academus.sln
> +# Visual Studio Version 17
reclama com a microsoft.

2023-05-04 20:06 UTC, rafaelgalvaolm commented on Academus.sln
> +EndGlobal
cego

2023-05-04 20:07 UTC, rafaelgalvaolm commented on .gitignore
> +.fake
feito

2023-05-04 20:08 UTC, rafaelgalvaolm commented on Core/Interfaces/Repositories/IUsuarioRepository.cs
>  }
feito

2023-05-04 20:08 UTC, rafaelgalvaolm commented on Data/Repositories/UsuarioRepository.cs
> +            var entity = await _dbContext.Set<Usuario>().FindAsync(id);
feito

2023-05-04 20:08 UTC, rafaelgalvaolm commented on Web/Controllers/UsuarioController.cs
> -            await _usuarioRepository.Deletar(idUsuario.Id);
feito

2023-05-04 20:09 UTC, rafaelgalvaolm commented on Web/ViewModels/Usuario/BuscarUsuarioViewModel.cs
>  }
ja estava

2023-05-04 20:10 UTC, rafaelgalvaolm commented on Web/Views/Usuario/_Cadastrar.cshtml
>        <hr>
feito

2023-05-05 11:17 UTC, thofalbo approved these changes

2023-05-05 12:18 UTC, merged